# Dependencies
markdown:         maruku
highlighter:      pygments

# Permalinks
permalink:        pretty

# Setup
title:            'Meave'
tagline:          'Meave Labs Blog'
description:      'Meave Labs Blog'
url:              http://meave-labs.github.io
baseurl:          /

author:
  name:           'Daniel R. Fiala'
  url:            https://meave-labs.net

paginate:         5

# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/meave-labs/meave-labs.github.io
